### PR TITLE
Adds webpack, validator, directory

### PR DESCRIPTION
**Pull request by gidsi**
I was playing a bit aroung, merge if you like, toss if you don't (but get the header and footer background before ;)).

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks, nice.

Can you add some build instructions to the README? I built the webpack bundles, but the lektor server doesn't seem to use those.

**Comment by gidsi** [comment]
> Thanks, nice.
> 
> Can you add some build instructions to the README? I built the webpack bundles, but the lektor server doesn't seem to use those.

Oh, shoot, forgot about that. Added it now!

**Comment by dbrgn** [comment]
Oh, the lektor webpack integration is cool. But I still don't get any proper styling when starting the server this way...

img

**Comment by gidsi** [comment]
> Oh, the lektor webpack integration is cool. But I still don't get any proper styling when starting the server this way...

That's weird. Can you check the log? 
It should also generate a `gen` folder in `assets/static` with a style.css in it, is that there? I'm going to fix the Dockerfile to check again, maybe I've something installed globally that is missing in the package.json or similar.

**Comment by gidsi** [comment]
Dockerfile also works as intended so far, don't know what the problem could be. 
Does the Dockerfile work on your end too?

**Comment by gidsi** [comment]
@dbrgn apparently there was a version conflict that caused problems. I've raised them and it doesn't seem to be a problem anymore. Can you confirm?

**Comment by dbrgn** [comment]
Merged, thanks!

**Pull request closed without merging**
