### PR TITLE
add open/closed image service

### PR DESCRIPTION
**Pull request by niccokunzmann**
This adds a configurable open/closed service.

https://ammanvms.github.io/SpaceAPIStatusImage/

### CODE REVIEW

**Comment by dbrgn** [comment]
Seems broken right now?

screenshot-20220806-115148

**Comment by niccokunzmann** [comment]
Thanks for testing ... The problem is that pythonanywhere does not allow me to connect to everywhere.... I will use Heroku..

**Comment by niccokunzmann** [comment]
Okay deplaoyed..
image

- I added a Heroku deployment
- I made sure that there are default badges available

Would you like to check again?

**Comment by dbrgn** [comment]
Nice, thanks!

**Comment by niccokunzmann** [comment]
Thanks! Spaceapi is quite cool and useful!

**Comment by niccokunzmann** [comment]
Good feedback. I guess, you would like to see something there...
At the moment, it works only if the icon field is filled.
It works with Amman Valley MakerSpace and others.

I guess, we can open an issue to add default pictures.

**Pull request merged**
