### PR TITLE
New Website

### PR DESCRIPTION
**Pull request by dbrgn**
Created using [Lektor](https://www.getlektor.com/). Work in progess.

### CODE REVIEW

**Comment by rnestler** [comment]
@dbrgn How is this coming along? If we don't expect to merge this soon I'd update the page with links to the new directory location.

**Comment by rnestler** [comment]
See https://github.com/SpaceApi/website/pull/34.

**Comment by dbrgn** [comment]
Yep, probably better to update the current website first.

**Comment by dbrgn** [comment]
@rnestler @gidsi ready for review! :tada:

**Pull request merged**
