### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by buzztiaan**

### CODE REVIEW

**Comment by dbrgn** [comment]
Oh, it seems that this is even an error in the current spec! Can you fix it in the 0.14 draft? https://github.com/SpaceApi/schema/blob/master/14-draft.json

@gidsi @rnestler should we also fix this in the 0.13 version as an error, or should we avoid potentially incompatible changes? does anyone currently use this key?

**Comment by buzztiaan** [comment]
sure thing, 14-draft fix is here ; https://github.com/SpaceApi/schema/pull/38

**Comment by rnestler** [comment]
> @gidsi @rnestler should we also fix this in the 0.13 version as an error, or should we avoid potentially incompatible changes? does anyone currently use this key?

Hmm I don't think we should change the schema of a version once published.

**Comment by dbrgn** [comment]
Ok, then let's stick with the old version of the docs until 0.14 is released!

See https://github.com/SpaceApi/schema/pull/38

**Pull request closed without merging**
