### PR TITLE
Add Member Matters to the provide an endpoint page

### PR DESCRIPTION
**Pull request by jabelone**
* Added Member Matters to the provide an endpoint page
* Added .DS_Store to .gitignore for macOS devs

An example instance can be seen on my makerspace's portal here for reference: https://portal.brisbanemaker.space/api/spacedirectory/

### CODE REVIEW

**Comment by rnestler** [comment]
@jabelone Can you rebase your branch? We had problems with the CI config, which should be fixed now.

**Comment by dbrgn** [comment]
Regarding the ` .DS_STORE` commit, I'm not a fan of that, since this is something that should typically be added to your user- or system-wide gitignore instead because it is specific to your operating system. You can find the location of your systemwide gitignore with `git config --get core.excludesfile`. I'd be fine with adding it to our `.gitignore` though since it doesn't hurt either.

Additionally, the filename is actually wrong, it should be `.DS_Store`. All-uppercase only works because macOS has a case-insensitive file system by default, but it won't match the file if the file system is case sensitive.

It would be great if you could either update or remove that commit.

**Comment by jabelone** [comment]
@rnestler and @dbrgn I have updated and rebased. Thanks!

**Review by rnestler — APPROVED** [review]
LGTM, but I'd like for somebody else of the SpacaAPI team to approve as well.

**Review by dbrgn — APPROVED** [review]
LGTM!

**Pull request merged**
