### PR TITLE
Added Hacker Hotel Spacestate to possible endpoints.

### PR DESCRIPTION
**Pull request by jhaand**
As discussed in this issue https://github.com/SpaceApi/website/issues/123, I added the Hacker Hotel Spacestate to the listed endpoints. 

I will add some more pictures and schematic later on.

### CODE REVIEW

**Comment by jhaand** [comment]
@dbrgn: Can you explain why the tests do not run?

**Comment by dbrgn** [comment]
Ah, it's a misconfiguration in the CI config! I think it should be fixed with #125. Could you rebase against `master`?

**Comment by jhaand** [comment]
I merged the new master into my branch. It should work now.

**Comment by jhaand** [comment]
The 'Build website' task is still not running. Do I need to merge the change to my master branch and submit a PR for that? 
Or do something else?

**Comment by jhaand** [comment]
That seemed to work on my end. 
https://github.com/jhaand/website_spaceapi/actions/runs/4345167269

**Comment by dbrgn** [comment]
> The 'Build website' task is still not running. Do I need to merge the change to my master branch and submit a PR for that? Or do something else?

No, that's due to GitHub: First-time-contributors need their CI pipelines to be approved by a maintainer 🙂

I just did that, CI is running now.

**Comment by dbrgn** [comment]
The CI change is not needed, I'll revert it directly on your branch.

**Comment by dbrgn** [comment]
Tested successfully, thanks!

**Comment by jhaand** [comment]
Thank you. Great to see it worked out in the end.

**Pull request merged**
